# Generated by Django 5.2.12 on 2026-03-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
